// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lyocpojcweyvoimnsfen.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx5b2Nwb2pjd2V5dm9pbW5zZmVuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1MjE4ODMsImV4cCI6MjA3MDA5Nzg4M30.FsAvm9tW646W8vvbLmhwbqyZrkAzlnGCByF_ms9DIvw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});